[cloudflare]
api_key = ""

[roundcube]
base_url = "https://example.com/admin"
username = "admin@example.com"
password = ""
blacklisted = [ "admin" ]

[variables]
domain = "example.com"
domains = [ "google.com" ]